### ISSUE TITLE
Add possibility to mark test as Passed, Failed and add bug from Test Info page

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/reporting#1272]
**Description:**
Add possibility to mark test as Passed, Failed and add bug from Test Info page.
Now after reviewing logs, video, etc we have to navigate back to the test suite and search for the test you reviewed to mark it or add bug.

**Comment by nsidorevich** [comment]
Sounds reasonable, @hursevich we might wanna enhance UI a bit here.

**Comment by vdelendik** [comment]
already delivered and available in prod
