### ISSUE TITLE
Add test rail run name to general testRun info

### ISSUE THREAD

**Issue by kolyakrasnik** [zebrunner/reporting#1284]
As user I would like to see which test rail run name was used by automation in case of enabled test rail integration. Currently I can get this info only in parameters for test run, what is not so convenience, especially for manual guys and customers.

**Comment by vdelendik** [comment]
@kolyakrasnik  we can think about adding it as string artifact on carina level.
So all tests inside test run will have the same testrail run name

**Comment by hursevich** [comment]
Need more details for that feature.

**Comment by vdelendik** [comment]
closing as not enough info provided
