### ISSUE TITLE
Service to launch job via Zafira in background and foreground

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#1319]
To make efficient way to integrate QA infrastructure into the dev Pipeline it would be nice to have separate end-point in Zafira for:
- launching job with args in background. This option should retun 200 if job was launched successfully.
- launching job with args in foreground. This option should wait till the timeout and return ZafiraReport as a String 

**UPD 10-15-2019:** This one belongs to Zafira Client and should be moved from here. Webhooks should come handy for this requirement.

**Comment by nsidorevich** [comment]
@Boniara let's keep this in mind while we work on new client. No action required for this one right away.

**Comment by vdelendik** [comment]
closing as obsolete. moreover, webhook feature was disabled as I know
