### ISSUE TITLE
Provide possibility of rebuilding certain failed test/tests 

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/reporting#1544]
With the current implementation, rebuild testrun gives an opportunity to rebuild either all tests in testrun or all failed tests. And it would be nice to have a third option: rerun only failed tests, which were chosen by user, e.g. when only specific test method was fixed and there's no necessity in running other failed tests again
<img width="528" alt="RebuildTestrun" src="https://user-images.githubusercontent.com/21850997/57515112-8f2dd400-731a-11e9-84f3-216c51f5fe63.png">

**Comment by nsidorevich** [comment]
@hursevich do we plan to work on this anytime soon? we'll need to alter current UI flow somehow...

**Comment by vdelendik** [comment]
closing as won't fix
