### ISSUE TITLE
Test run can't be renamed in Zafira if jenkinsQueueRegistration=true

### ISSUE THREAD

**Issue by dmitry-minchuk** [zebrunner/reporting#1673]
When I created a test suite with some name:
`<suite verbose="1" name="Web tests">`
and then created jenkins job using this suite and ran it, in Zafira it could be viewed as "Web tests", but when I tried to change its name to 
`<suite verbose="1" name="Mobile tests">`
nothing changed in Zafira - it is has been still shown as Web tests. To handle this I had to add jenkinsQueueRegistration parameter to my suite, set its value to false, reregister repository, reran it and only after that test run name changed to "Mobile tests".

**Comment by tsvrko** [comment]
Based on queued tests creation specifics (when we queue test, we just get test suite from previous run as is and don't have any opportunity to change it) the simplest solution is to rescan jobs with jenkinsQueueRegistration=false once and then everything will work as expected (or even make jenkinsQueueRegistration=false by default). @vdelendik @hursevich what do you think?

**Comment by vdelendik** [comment]
it should be fixed already
