### ISSUE TITLE
Add support for bitbucket and gitlab for zafira integration

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#1681]
**UPD 08-28-2020:**
Agreed to move integration completely onto the reporting ui. For now github including corporate one can be registered by "./zebrunner.sh setup" configurator.
In 1.12 release valid integration on reporting should be established via ui inclusing multiply integration support for each provider. Let's say I'd like to integrate cloud and enterprise github simultaniously.
Adding repository will provide valid scm properties to CI jobs.

Potentially it might simplify pipeline logic for cloning: https://github.com/qaprosoft/qps-pipeline/issues/896

**UPD 10-14-2019:**
Request from @vdelendik:

1. move scm (github, bitbucket, gitlab) integration into the Zafira UI. Make sure to support host to be able to register corporate systems
2. For each SCM item save id/secret values in DB:
`GITHUB_CLIENT_ID=...`
`GITHUB_CLIENT_SECRET=`
3. Add Repo functionality before opening SCM callback url should provide choice for all registered SCM items

As per #1646 :
Test Launchers -> Add repo functionality doesn't work for corporate github url. Github authorization url always opened usin github.com only

**Comment by vdelendik** [comment]
1) move scm (github, bitbucket, gitlab) integration into the Zafira UI.
Make sure to support host to be able to register corporate systems
2) For each SCM item save id/secret values in DB:
GITHUB_CLIENT_ID=...
GITHUB_CLIENT_SECRET=
3) Add Repo functionality before opening SCM callback url should provide choice for all registered SCM items

**Comment by vdelendik** [comment]
it seems to be fixed in 1.9+. let's test and close if ok

**Comment by okamara** [comment]
Integration with jenkins and reporting is not working correctly for launchers https://github.com/zebrunner/zebrunner/issues/274

**Comment by vdelendik** [comment]
feature should be removed in 1.24 at all, i.e. no more launchers and ability to register integration with any git implementation from UI. CI layer aka jenkins is the only one to register repo, generate jobs and run something

**Comment by okamara** [comment]
Verified on dev., fixed.
