### ISSUE TITLE
Linked to a wrong Jira  URL

### ISSUE THREAD

**Issue by tbdyzm** [zebrunner/reporting#1721]
In dashboard I click into Personal, in Personal Failures widget, BUG linked to a wrong url http://ip:port/browse/browse. While in test laucher page, it linked to a correct url http://ip:port/browse.
![1](https://user-images.githubusercontent.com/41499236/63220912-6479d400-c1c3-11e9-8830-4a191f047815.png)
![2](https://user-images.githubusercontent.com/41499236/63220914-68a5f180-c1c3-11e9-8721-9b09898efbba.png)
![3](https://user-images.githubusercontent.com/41499236/63220916-6cd20f00-c1c3-11e9-986f-dd2715fece26.png)
![4](https://user-images.githubusercontent.com/41499236/63220917-7196c300-c1c3-11e9-9c3f-f8889ad25555.png)

**Comment by vdelendik** [comment]
already fixed on widgets template side. When you add Failures analysis widget you can specify your own url to which actual ticket will be concatenated. i.e. this feature allow to support references to github/gitlab etc issues as well

**Comment by okamara** [comment]
Will be tested on customer side.
