### ISSUE TITLE
add links to TestRail cases to Attachments page

### ISSUE THREAD

**Issue by Litsvin** [zebrunner/reporting#1759]
As page with attachments (logs, screenshots, video, etc.) is the place where all test data is aggregated, it would be convenient to have links to TestRail cases there as well.

**Comment by Litsvin** [comment]
Speaking of birds...
I think, that to add possibility to pass/fail to this screen could be convenient too.

**Comment by vdelendik** [comment]
already implemented. links to testrails are registered as labels
