### ISSUE TITLE
incorporate TEST_CASE_HEALTH_VIEW views into the other views

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#1774]
investigate possibility to decommission separate TEST_CASE_HEALTH_VIEW view and reuse existing last24hours, last32days, total_view etc to show heath check stability.
1st one is rather limited and doesn't provide info about test suite.

**Comment by nsidorevich** [comment]
Owned by @vdelendik and will be implemented by him.

**Comment by vdelendik** [comment]
done in 1.19 version. TEST_CASE_HEALTH_VIEW removed at all, all widgets reorganized to use regular sql query wihtout any materialized views as we already have limitation by testcase id
