### ISSUE TITLE
Improve 'known issue' feature

### ISSUE THREAD

**Issue by kolyakrasnik** [zebrunner/reporting#1778]
Currently we analyze a big part of issue's stack trace, so, any updates cause that zafira not able to determine known issues. Is it any way to improve this flow?

**Comment by kolyakrasnik** [comment]
Let's assume that we have some general flow of registration or log in and there is scope of known issues in the app.  One day devs added additional screen during registration or log in (for example confirm privacy or enable notifications).  As a result all known issues will be lost.

**Comment by katedkm** [comment]
It would be a good point and opportunity to have ability exclude from a test log all dynamic capabilities with alphanumeric dynamic part that can influence to a logs comparison process.
e.g. userDataDir: /tmp/.com.google.Chrome.IbEp4t

**Comment by vdelendik** [comment]
moved to another repo
