### ISSUE TITLE
Set 'run_exists=true' when rerun

### ISSUE THREAD

**Issue by deNatallia** [zebrunner/reporting#1794]
Choose run in Zafira that has already been written in testrail.
Click 'Rerun' it.

**Expected result:** existing test run is updated in testrail
**Actual result :** new run is created in testrail

Because of parameter 'run_exists' is FALSE by default. So it should be set to TRUE for rerunning.

**Comment by nsidorevich** [comment]
Not reproduced since was already fixed by @tsvrko

**Comment by deNatallia** [comment]
It is still repro.
1. Run any job with parameter 'run_exists' = false and 'testrail_enabled' = true -> Results were published in testrail in run with name 'Testrun_1'.
2. Rerun this run using zafira

**Expected result:** Results were updated in 'Testrun_1'

**Actual result:** New testrun 'Testrun_1' with results was created

**Comment by vdelendik** [comment]
closing as already fixed in pro version. CE integration with testrail is too limited now
