### ISSUE TITLE
provide valid error message about non started zafira

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#1869]
**Description**
zafira-ui shows error message like "projects can't be loaded"when zafira is not started yet.
We should add explicit verification for that and tel about non started zafira and maybe refer to the logs or ask admin.

**Steps to reproduce**
1. Stop zafira container
2. Open zafira url
3. invalid error message is shown

**Environment**
[Make sure to specify Zafira versions you see at login page]
UI version: 1.25
API (back-end) version: 4.1.79

**Comment by nsidorevich** [comment]
I've encountered this several times myself. My understanding is that we do not have proper error handling on FE side (like in the case when back is stopped - there's obviously nothing to expect from API). @danymill could you please take a look and see if we can display something meaningful?

**Comment by nsidorevich** [comment]
@danymill you can leverage this endpoint: https://stage.qaprosoft.farm/zafira-ws/swagger-ui.html#/application-health-controller/getStatus

**Comment by danymill** [comment]
Available on UI from v. `1.378-SNAPSHOT`

**Comment by vdelendik** [comment]
fixed based on above comment
