### ISSUE TITLE
In case of rerun failures, Zafira "progress chips" are updated to old results on each execution of test

### ISSUE THREAD

**Issue by ydaroshka** [zebrunner/reporting#1888]
**Description**
When fo some reasons we want to make a rerun failures and in the previous execution we had sone aborted or failed test. Each time when new test passed or failed during the rerun the `progress chips` are updated to old results.

**Preconditions**
- Test run was finished 
- Rerun was started 
- Few tests were executed on rerun 

**Steps to reproduce**
[guest user, ( I think ). Zafira shows `ROLE_USER` bot sure what it means]
1. Go to <zafira_home>/app/tests/runs
2. Find "Regression suite" ( i used filter by the name ) 
3. Refresh page to make sure that we have the latest results
4. Wait until one test executes 

**Actual behaviour**
After execution, the "progress ships" are changed to the old view which Zafira showed before rerun execution

**Expected behaviour (if known)**
they should be actual all the time 

**Environment**
2019 Zafira all rights reserved
ui v.1.26 | server v.4.1.80 | client v.4.1.64
Chrome browser: Version 78.0.3904.108 (Official Build) (64-bit)

**Attachments**
user role: 
<img width="713" alt="Screenshot at Nov 26 13-04-08" src="https://user-images.githubusercontent.com/28759215/69620225-0ecc8780-104e-11ea-9ce9-6ed5252b31d5.png">

**Comment by nsidorevich** [comment]
@Boniara let's double-check what is actually going on on BE side once we calculate those number for rerun.

**Comment by brutskov** [comment]
Will be available in server v. 1.1.0

**Comment by brutskov** [comment]
@ydaroshka give your feedback please

**Comment by nsidorevich** [comment]
@ydaroshka false alarm, we still have minor items to fix.

**Comment by vdelendik** [comment]
closing as obsolete
