### ISSUE TITLE
Refactor TestRunService

### ISSUE THREAD

**Issue by nsidorevich** [zebrunner/reporting#1892]
**Description**
Zafira's `TestRunService` is 800+ lines long, contains dozens of private and public method, depends on ridiculous amount of other classes. Plus it contains legacy TODOs and comments that were never addressed. We need to refactor this one so it would be easier to troubleshoot, support and maintain. Let's get rid of long methods, name private methods in a way so their functional purpose would be clear and straightforward and reduce service's cyclomatic complexity.

**References**
https://en.wikipedia.org/wiki/Cyclomatic_complexity

**Comment by vdelendik** [comment]
closed as obsolete
