### ISSUE TITLE
Zebrunner doesn't have email configuration

### ISSUE THREAD

**Issue by raviAegon** [zebrunner/reporting#1906]
**Description**
Zebrunner doesn't have email configuration through which we can schedule Dashboard to email recipients as QPS-infra Zafira has a configuration to send dashboard on email.

**Comment by Boniara** [comment]
@raviAegon, email integration is setup on your instance and you should be able to send dashboards and widgets via UI. Do you really need any automation in sending boards by schedule?

**Comment by raviAegon** [comment]
Boniara, Yes it would be very helpful to us. By when it can be possible.
Kindly let me know if you need any details.
Our Zebrunner account: Aegon-Zafira

**Comment by vdelendik** [comment]
@raviAegon please ping me directly with a request about concrete board and schedule. We can organize it for cloud users as a service

**Comment by vdelendik** [comment]
closing as won't fix especially in CE part
