### ISSUE TITLE
Add possibility to re-send Run information in Slack after manual review 

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/reporting#1921]
**Description**
Now in slack integration, we can get result of runs only before review. 

**Value**
It will be really useful to make the possibility of re-sent actual results in Slack after manual review. 

**Additional context**
Maybe with some additional marker that these results are AFTER manual review.

**Comment by vdelendik** [comment]
closing as won't fix in CE, PRO part already has implementation
