### ISSUE TITLE
Add rerun with parameters

### ISSUE THREAD

**Issue by Litsvin** [zebrunner/reporting#1928]
**Description**
I want to have a possibility to do rerun with changed parameters.

**Value**
Let's imagine that I have a test report with 20%, I do fixes and want to rerun failed tests. But those fixes could potentially brake out test code, or/and I need to change thread_count.

**Comment by hursevich** [comment]
We have to design the correct flow, are you still need to rerun only failures or the whole suite?

**Comment by Litsvin** [comment]
I think both variants are possible - whole suite and fails only

**Comment by vdelendik** [comment]
rerun failures or everything already available in reporting
