### ISSUE TITLE
Widget preorder is not displayed properly

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/reporting#1964]
**Steps to reproduce**
Steps:
1. Login to Zafira
2. Open dashboard
3. Select "New Widget"
4. Click on "MILESTONE DETAILS"
5. Click on "PASS RATE"

**Actual behavior**
<img width="2044" alt="Screen Shot 2019-12-20 at 16 58 19" src="https://user-images.githubusercontent.com/56070333/71259686-0ebc6080-234a-11ea-88df-b655ddd5aff4.png">
https://www.dropbox.com/s/at7lbtsomu7xe56/online_widget.mp4?dl=0

**Expected behavior**
<img width="2040" alt="Screen Shot 2019-12-20 at 17 01 33" src="https://user-images.githubusercontent.com/56070333/71259841-64910880-234a-11ea-9651-1169be5f119a.png">

**Environment**
ui v.1.29.RC2 | server v.4.1.82.RC5 | client v.4.1.65

**Comment by vdelendik** [comment]
out-of-dated
