### ISSUE TITLE
Azure storage support for screenshot storage (currently S3)

### ISSUE THREAD

**Issue by ghost** [zebrunner/reporting#1995]
**Description**
Please add Azure storage support similar to that of amazon s3

**Value**
Valuable to the users who want to use Azure cloud

**Additional context**
Add any other context or artifacts (screenshots/sketches/project references with similar functionality) about the feature request here.

**Comment by nsidorevich** [comment]
@hursevich @brutskov let's see if we can achieve this with minio

**Comment by vdelendik** [comment]
in 1.9+ we released embedded s3 compatible minio storage which can be used instead of AWS S3.
