### ISSUE TITLE
Cannot use linked Failure UI dump

### ISSUE THREAD

**Issue by Litsvin** [zebrunner/reporting#2010]
**Description**
Cannot use linked Failure UI dump

**Steps to reproduce**
If you have some failed test in test report (Android mobile)
There's a link to download UI dump
![Screen Shot 2020-01-22 at 4 00 40 PM](https://user-images.githubusercontent.com/18280686/72896256-5e6abf00-3d30-11ea-8156-ce314431abcc.png)
But only one file is downloaded meanwhile to build an element tree 2 files are required
![Screen Shot 2020-01-22 at 4 01 47 PM](https://user-images.githubusercontent.com/18280686/72896306-83f7c880-3d30-11ea-87a8-43b499cadfab.png)

**Environment**
ui v.1.32 | server v.4.1.84 | client v.4.1.65

**Comment by vdelendik** [comment]
already fixed. zip archive contains sreen and uix file
