### ISSUE TITLE
Add history logs in test details

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/reporting#2038]
**Description**
History logs about changing status for the test should be useful.
Who and when marking it as Passed, linked an issue, etc. 
Also, it will be useful to see how many retries have been done to get the current result.

And adding the possibility to mark test for an update. (test case or design was changed). Currently, it will just fail without any readable note. 

**Value**
It will be easier to understand real statistics after reviewing by the manual team.

**Comment by vdelendik** [comment]
already fisnihed
