### ISSUE TITLE
Dashboard attributes do not apply to widgets immediately after adding

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/reporting#2063]
**Steps to reproduce**
1. Login to Zafira
2. Open general dashboard
3. Click edit dashboard
4. Add Key= PLATFORM value=api
5. Click ADD
6. Click Save

**Actual behavior**
Widgets are not updated to the according key-value. only after refreshing the page

**Environment**
ui: 1.35.RC2
server: 4.1.88.RC4
client: 4.1.65

**Comment by vdelendik** [comment]
closing as won't fixed. only admin should refresh a page to see updates
