### ISSUE TITLE
Checkbox opposite the passed test run is selected after rerun only failures for multiple test runs 

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/reporting#2088]
**Steps to reproduce**
1. Login to Zafira
2. Open test runs tab
3. Select several test runs (passed and failed)
4. Click on fab button
5. Select rerun
6. Select OK
7. Select OK

**Actual behavior**
Checkbox opposite the passed test run is selected
<img width="2023" alt="Screen Shot 2020-03-09 at 17 21 32" src="https://user-images.githubusercontent.com/56070333/76221803-b1d69500-622a-11ea-811f-2bb39d1afb86.png">

**Environment**
ui: 1.389-SNAPSHOT
server: 1.583-SNAPSHOT
client: 1.0-SNAPSHOT

**Comment by vdelendik** [comment]
closing as obsolete
