### ISSUE TITLE
Test with with similar names on result page

### ISSUE THREAD

**Issue by dzmitry-pinchuk** [zebrunner/reporting#2118]
**Description**
Only one test from tests with similar names is shown in result

**Steps to reproduce**
Below are the steps to reproduce the behavior:
1) Create two tests with similar names in different classes.
2) Execute run with this tests.
3) Review result page.

**Actual behavior**
Only one test from tests with similar names is shown in result

**Expected behavior (if known)**
All tests with similar names shown in result

**Environment**
UI version: ui v.1.1.0
API (back-end) version: server v.1.1.0

**Comment by vdelendik** [comment]
closing as out-of-dated. @dzmitry-pinchuk, please test
