### ISSUE TITLE
To Add Quarter and Month option in Pass Rate Bar Widget

### ISSUE THREAD

**Issue by NirajAegon** [zebrunner/reporting#2148]
As in Pass Rate Calendar widget , can we have Quarter and Month option in Pass Rate Bar Widget. Ti view historic view in Bar quarter/ monthly at least last three months.

**Comment by vdelendik** [comment]
fixed as part of 1.20 release

**Comment by okamara** [comment]
Verified on dev branch, fixed.
<img width="110" alt="Screen Shot 2021-02-25 at 2 14 34 PM" src="https://user-images.githubusercontent.com/32964663/109145733-f036ce00-7773-11eb-93a6-c8c3dd273f82.png">
