### ISSUE TITLE
Visual issue on launcher window on mobile version

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/reporting#2152]
**Steps to reproduce**
1. Login to Zebrunner **on mobile** (admin/user)
2. Open test runs
3. Click on Launcher button
4. Select any laucher

**Actual behavior** 
White stripe on the right. 
![Image from iOS (1)](https://user-images.githubusercontent.com/56070333/84324013-8bedc300-ab80-11ea-980c-75309e65a7dc.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/56070333/84324682-bbe99600-ab81-11ea-8351-78a679d170ee.png)

**Environment**
Safari+Chrome
ios 13.5.1
ui: 1.5.0.RC1
server: 1.5.0.RC1

**Comment by vdelendik** [comment]
closing as out-of-dated
