### ISSUE TITLE
 In the top of the test run user see previous number of passed/failed/skipped test cases. 

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2160]
Precondition:
Run web or api regression job

Steps to reproduce
1. Rerun failed test cases in Test Run
Expected: 1 or 2 failed test should change status to Passed in test run and in the top of the test run
Actual result: in the top of the test run user see previous number of passed/failed/skipped test cases. 
Note: After Reload the page issue is fixed.
Environment
Tested via qps-infra:develop; jenkins-master:5.1-beta3;pipeline-develop
zebrunner:
ui: 1.3.0
server: 1.3.1
<img width="328" alt="Screen Shot 2020-06-18 at 4 19 57 PM" src="https://user-images.githubusercontent.com/32964663/85031375-44ba9000-b187-11ea-9ba5-bef6d8518adc.png">

**Comment by vdelendik** [comment]
fixde indirectly. @okamara, please retest

**Comment by okamara** [comment]
Verified. Fixed.
