### ISSUE TITLE
Arrow is under the video on mobile version

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/reporting#2163]
**Below are the steps to reproduce the behavior:**
1. Login to Zebrunner on mobile
2. Open test with 2 drivers
3. Click on arrow on the video

**Actual behavior**
Left arrow  is under the video on mobile version

**Environment**
ui: 1.6.0.RC1
server: 1.6.0.RC3

IOS 13.5.1

**Attachments**

![IMG_1634](https://user-images.githubusercontent.com/56070333/85590471-1ccaa100-b64d-11ea-801f-4350bbf8330b.PNG)

**Comment by vdelendik** [comment]
it should be already fixed I guess

**Comment by okamara** [comment]
verified on dev. branch, fixed.
