### ISSUE TITLE
Navigation sidebar is broken on mobile version

### ISSUE THREAD

**Issue by lmikhadyuk** [zebrunner/reporting#2164]
**Steps to reproduce**
1. Login to Zebrunner on mobile

**Actual behavior**
https://www.dropbox.com/s/v3heayqu6ptwf1p/IMG_1623.MP4?dl=0

**Environment**
ui: 1.6.0.RC1
server: 1.6.0.RC3

IOS 13.5.1

**Comment by vdelendik** [comment]
in 1.24 mobile version will be redesigned completely

**Comment by dhreben** [comment]
Fixed.

IOS 14.4.2
ui: 1.23.0.326-SNAPSHOT
server: 1.23.0.669-SNAPSHOT
