### ISSUE TITLE
move s3 compatible mino service into the independent repository

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2186]
minio s3 compatible storage should be generated as independent repository with their own docker-compose, .env etc.
later it should be registered as reporting sub-module. During setup script execution we should provide an option to choose AWS S3 and enable embedded minio services

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/reporting/pull/2197

to test there is enough to clone just reporting repo, start it and login
```
git clone --recurse-submodule --branch "develop" https://github.com/zebrunner/reporting.git
cd reporting 
./zebrunner.sh start
```

As result we should have:
1) all reporting containers up&running including sub-modules minio ones:
- minio/mc:RELEASE.2020-05-28T23-43-36Z
- minio/minio:RELEASE.2020-06-03T22-13-49Z
2) be able to login into the reporting tool using admin/changeit

**Comment by okamara** [comment]
Tested. It is possible to login using admin/changeit.
I only see errors in console log during start reporting service.

**Comment by okamara** [comment]
Reverified after removing volumes and all containers.Fixed.
