### ISSUE TITLE
improve "setup" process 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2190]
by default configurable .env and var files should be placed using "*.original" naming convention.
during setup we have to update them using user content and rename, for example:
.env.original -> .env

**Comment by vdelendik** [comment]
finished: https://github.com/zebrunner/reporting/pull/2194

test scenario:
1. clone current reporting repo, switch to develop branch
```
git clone https://github.com/zebrunner/reporting.git
cd reporting
git checkout develop
```
2. try to start:
```
./zebrunner.sh start
```
->  warning message should appear
WARNING! unable to proceed without setup procedure! Please, execute:
./zebrunner.sh setup

3. setup reporting and start
```
./zebrunner.sh setup
# provide valid protocol, host and port
./zebrunner.sh start
```

4. reporting is up&running, default admin can log

**Comment by okamara** [comment]
Verified. Fixed.
