### ISSUE TITLE
made "admin/changeit" as default reporting user

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2193]
default administrator user should be generated as admin/changeit instead of qpsdemo/qpsdemo.
as part of the ticket **obligatory update README docs!**

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/reporting/commit/ffbee13e9c4cf4f0aed82a86d64d92e2a3c0ae78

**Comment by okamara** [comment]
Verified. Fixed.
