### ISSUE TITLE
Test case results can't be loaded on the page in zafira

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2195]
**Steps to reproduce**
1. Run Web, Api tests via Jenkins
2. Open Zafira Test runs
3. Open web test or api test

**Actual behavior**
Test case result logs can't be loaded on the page

**Expected behavior (if known)**
Test case result logs are visible on UI

**Environment**

UI version: 1.18
API (back-end) version:1.18

**Attachments**
<img width="1437" alt="Screen Shot 2020-08-12 at 1 20 38 PM" src="https://user-images.githubusercontent.com/32964663/90007171-ea2f4300-dca2-11ea-9a92-df58fe396e05.png">
<img width="1435" alt="Screen Shot 2020-08-12 at 1 16 47 PM" src="https://user-images.githubusercontent.com/32964663/90007188-f1565100-dca2-11ea-950d-c84cce5ae7cd.png">

**Comment by vdelendik** [comment]
fixed in 1.9

**Comment by dhreben** [comment]
**Steps to reproduce**:

1.Run Web, Api tests via Jenkins
2.Open Zafira Test runs
3.Open web test or api test

**Actual results**: Test case result logs can't be loaded on the page

**Expected results:** (if known) Test case result logs are visible on UI

Environment:

ui: 1.16.0
server: 1.16.1.RC2


<img width="1260" alt="Screenshot 2020-12-01 at 22 37 30" src="https://user-images.githubusercontent.com/50950954/100788205-cf393800-3425-11eb-876a-d25f88278030.png">

<img width="1289" alt="Screenshot 2020-12-01 at 22 38 31" src="https://user-images.githubusercontent.com/50950954/100788307-f55ed800-3425-11eb-813b-2371131ed21e.png">

**Comment by vdelendik** [comment]
fixed for 1.16

**Comment by dhreben** [comment]
Fixed.
