### ISSUE TITLE
In email notifications better to show all failures and skipped at the beginning. And add TestRailIds if they present. 

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/reporting#2199]
**Description**
If we have a lot of tests (100+) and waiting for email notification (if Zebrunner is not accessible for example) it is better to see all failures at the beginning (for example sorting failures and skips at the beginning of email). And with added TestRails ids (if they present).

**Value**
It will help to recognize all failures quicker and in urgent cases will help the Manual team find test cases by visible testrail id. 

**Additional context**

**Comment by vdelendik** [comment]
done in 1.9
