### ISSUE TITLE
SELENIUM integration is red in reporting service after configuration

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2204]
**Steps to reproduce**
Start Jenkins
Below are the steps to reproduce the behavior:
1. Go to reporting service Integration
2. Configure Selenium

**Actual behavior**
SELENIUM integration is red in reporting service after configuration

**Expected behavior (if known)**
SELENIUM integration is green in reporting service after configuration

**Environment**
[Make sure to specify Zebrunner versions you see at login page]
UI version:1.18
API (back-end) version:1.18

**Attachments**
<img width="450" alt="Screen Shot 2020-08-18 at 3 54 38 PM" src="https://user-images.githubusercontent.com/32964663/90515346-30851600-e16b-11ea-8058-375088b7a9a1.png">

**Comment by vdelendik** [comment]
also default url in CI is incorrect for embedded selenoid hub:
selenium_host=http://demo:demo@localhost/selenoid/wd/hub

**Comment by vdelendik** [comment]
yesterday it was fixed (jenkins, selenoid and mcloud should be enabled and green)

**Comment by okamara** [comment]
Verified. Fixed.
