### ISSUE TITLE
unable to start zebrunner-proxy without minio

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2205]
Minio storage is optional component. So when we don't have it enabled it shouldn't affect zebrunner-proxy.
to make it happen reference to minio should be organized via local $upstream_minio variable

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/reporting/commit/2e883b09dbba6be1817def8b5717a4ade4a63274

During setup answer "n" for Minio Storage and start everything.
You should be able to login into the reporting tool

**Comment by okamara** [comment]
Verified. Fixed.
