### ISSUE TITLE
logs are unavailable after elasticsearch container restart

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2206]
due to the upstream declaration usage zebrunner-proxy resolve elasticesearch container on the start. As only elasticsearch container crashed and recreated reporting nginx can't resolve new host.

we have to reorganize proxy configuration file to make resolving on the fly so any restart don't impact overall functionality

**Comment by vdelendik** [comment]
done. testing scenario should include:
1. clone from scratch using develop branch
2. setup, start and run any test with logs
-> on test info page logs are displayed
3. remove elasticsearch container
`docker rm -f elasticsearch`
-> After refreshing test info page no logs is available
4. `./zebrunner.sh start` to start missed elastic and wait 1 min
-> after refreshing test info page logs again are available

**Comment by okamara** [comment]
Verified. Fixed.
