### ISSUE TITLE
Drop down menu is not displayed for pick issue label

### ISSUE THREAD

**Issue by VitaliLiavitski** [zebrunner/reporting#2210]
**Description**
Drop down menu is not displayed for pick issue label

**Steps to reproduce**
1. Go to  test run results for example 'https://projectName.zebrunner.com/tests/runs/55166'
2. Sort by Failure
3. Select one failure, try to click by Pick issue label

**Actual behavior**
Drop down menu is not displayed

**Expected behavior (if known)**
Drop down menu is displayed and I can choose item

**Environment**
browser Safari 13.1
![Screen Shot 2020-08-21 at 13 53 09](https://user-images.githubusercontent.com/3008517/90883658-f019d800-e3b6-11ea-830b-65d900d3ce5b.png)

UI version: v.1.9.0
API (back-end) version: v.1.9.0

**Comment by vdelendik** [comment]
closing as fixed indirectly
