### ISSUE TITLE
do not share elasticsearch end-point outside

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2214]
http://hostname/elasticsearch/**indice**/_search?size=2

"size=2" is ignored when we do a call via NGiNX

**Comment by vdelendik** [comment]
there is no need to open elasticserach outside anymore. so let's use this ticket to remove /elasticsearch nginx rules at all. subj updated accordingly

**Comment by vdelendik** [comment]
moved to 1.12 milestone as in 1.1 we have to patch zebrunner-proxy/nginx.conf already.

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/reporting/commits/develop

test scenarion. After setup zebrunner from develop branch this url shouldn't be opened successfully anymore
http://your-host/elasticsearch/_cat

**Comment by okamara** [comment]
Verified on develop.Fixed.
