### ISSUE TITLE
Guide:Page with 404 error is opened

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2217]
**Steps to reproduce**
[Make sure to specify user role used to log in to Zebrunner]
Below are the steps to reproduce the behavior:
1. Go to https://zebrunner.github.io/documentation/guide/integrations/
2. Click on 'Edit'

**Actual behavior**
Page with 404 error is opened

**Expected behavior (if known)**
Page is opened without errors

**Comment by vdelendik** [comment]
fixed. CI/CD configured to publish updates immidiately after commit/push

**Comment by okamara** [comment]
Fixed.
