### ISSUE TITLE
Add the ability to filter by test suite

### ISSUE THREAD

**Issue by FredVaugeois** [zebrunner/reporting#2224]
It would be great to add a way to filter the test suite for the Zebrunner viewer. By test suite, I mean that blue-ish value versus "local" in this image:

![image](https://user-images.githubusercontent.com/26579806/94058423-fb459680-fdae-11ea-8ed9-3fb6a9ed96b3.png)

So basically, I'd like to be able to filter out the "local" test runs and only have the automated/jenkins ones.

**Comment by vdelendik** [comment]
it should be fixed in 1.22
