### ISSUE TITLE
Issues for start Reporting

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2225]
**Description**
There are issues with start reporting and impossible sign in after start

**Steps to reproduce**
1. git clone --recurse-submodule https://github.com/zebrunner/reporting.git && cd reporting
2. Run the application
./zebrunner.sh start
**Actual behavior** There is message in start log "- cp: cannot stat ‘configuration/rabbitmq/definitions.json.original’: No such file or directory"
3.Login to the application with default credentials admin/changeit:
**Actual behavior** Login is failed

Reporting log contains errors:
org.postgresql.util.PSQLException: FATAL: password authentication failed for user “postgres”
14:34
2020-09-24 11:33:25.718 ERROR [main] o.s.boot.SpringApplication: Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name ‘entityManagerFactory’ defined in class path resource [com/zebrunner/reporting/persistence/PersistenceConfig.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/reporting/pull/2226
it might be verified using zebrunner/zebrunner from develop branch (1.10 reporting is part of the infra now)

**Comment by okamara** [comment]
I see that 1.9.1 reporting is part of the infra now on develop.

**Comment by okamara** [comment]
Fixed.
