### ISSUE TITLE
postgres: max_connections=100 is not enough anymore

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2227]
We faced with the problems for auto-update of materialized views due to the not enough connections.
Current load is about 98-103 connections and as result cron processes can't establish new ones and failed. As result staistic data disappear from widgets and not available in the morning.
we have to find a way to double this value by default.
Workaround for existing envs:
`
docker exec -ti postgres bash
apt-get install nano
nano /var/lib/postgresql/data/postgresql.conf
#double max_connection 100->200
max_connections = 200
#save, exit and restart everything
`

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/reporting/commit/f207b22085633be43add965de3eb34329dccf5df

testing scenario:
1. clone reporting from develop branch recursively
```git clone --recurse-submodule --branch "develop" https://github.com/zebrunner/reporting.git```
2. temporary uncomment 5432 port in [docker-compose.yml(https://github.com/zebrunner/reporting/blob/f207b22085633be43add965de3eb34329dccf5df/docker-compose.yml#L18)
3. start just reporting with default settings
```./zebrunner.sh start```
4. using pgAdmin connect to your postgres. Defaul password is db-changeit (https://github.com/zebrunner/reporting/blob/f207b22085633be43add965de3eb34329dccf5df/configuration/reporting-service/variables.env.original#L17)
5. execute below query to ensure that default max_connections is 200 now:
```SELECT *
FROM   pg_settings
WHERE  name = 'max_connections';
```
![image](https://user-images.githubusercontent.com/4551455/94585532-d0fd4880-0288-11eb-9b2d-ac0ccec121c5.png)

**Comment by dhreben** [comment]
Verified.
<img width="731" alt="Screen Shot 2020-09-30 at 18 40 33" src="https://user-images.githubusercontent.com/50950954/94707724-71687100-034c-11eb-820d-83133e47d56e.png">
