### ISSUE TITLE
minio storage config mismatch for local project icons

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2230]
zebrunner: 1.1
reporting: 1.10

Project icons are uploaded but can't be displayed due to the mismatch in the rewrite rule for reporting/configuration/zebrunner-proxy/nginx.conf

old value:
`
        location ~ ^/(artifacts|assets|common|users)/ {
          limit_except GET {
            deny all;
          }

          proxy_set_header User-Agent "custom_secret_value";
          rewrite ^/(.*)$ /zebrunner/$1 break;
          proxy_buffering off;
          proxy_pass http://minio:9000;
        }
`

New rewrite is:
rewrite ^/(.*)$ /zebrunner/zafira/$1 break;

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/reporting/commit/d2f565ac16f63e29c1eabb9708c7492ac7459518

it should fix corrupted screenshots for web tests. But it might corrupt use-case when AWS S3 integration is needed.
So during the verification we have to setup and test both configs with minio storage and aws s3!

testing might be done using zebrunner/zebrunner (branch: develop).
Acceptance scenario: correctly displayed thumbnails and big screenshots.

**Comment by okamara** [comment]
Verified on dev.
