### ISSUE TITLE
001-general-definition.json.original rabbitmq definition can affect negativly mq setup on startup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2231]
001-general-definition.json.original file has dummpy credentials which are updated by setup process using user input.
As result we see that both files affected and one more queue and user registered using dummy credentials.
we have to find a way to exclude sharing 001-general-definition.json.original file into the container

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/reporting/commit/a596846d139104dd193b036aa181f7a949d7e617

testing scenario:
1. pull zebrunner/zebrunner recursively (branch: develop)
2. setup everything
Note: it is recommended to provide custom rabbitmq user and password
3. start everything
4. login into the rabbtmq and ensure that /rabbit-definitions/001-general-definition.json.original file is empty
```
docker exec -ti rabbitmq bash
cat /rabbit-definitions/001-general-definition.json.original
```
-> nothing is displayed

**Comment by okamara** [comment]
Verified. Fixed.
