### ISSUE TITLE
Failures analysis: Wrong url for report from the board

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2232]
**Steps to reproduce**

1. Go to '.Reporting Dashboard page'
2. Open Failures analysis page
3. Click on reporting url

**Actual behavior**
404 page is opened

**Expected behavior (if known)**
Report page is opened

**Environment**

UI version:1.12.0.RC2
API (back-end) version:1.12.0.RC1

**Comment by vdelendik** [comment]
@tsvrko need to find location where db-views.sql to fix views

**Comment by vdelendik** [comment]
fixed. we have to remove all reporting docker images manually!

**Comment by okamara** [comment]
Verified on dev. Link is wrong.

**Comment by vdelendik** [comment]
fixed in develop branch of zebrunner

**Comment by dhreben** [comment]
Fixed.
<img width="1233" alt="Screen Shot 2020-10-05 at 13 59 31" src="https://user-images.githubusercontent.com/50950954/95071865-008dd400-0713-11eb-9a79-fe8326cea6ea.png">
