### ISSUE TITLE
unable to launch default launcher job right after setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2233]
baed on the log we don't have default INTEGRATION_JENKINS_URL var which is used for default configuration stuff

job: {id: 1, name: "launcher", jobURL: "${INTEGRATION_JENKINS_URL}/job/public/job/launcher",…}
id: 1
jenkinsHost: "${INTEGRATION_JENKINS_URL}"
jobURL: "${INTEGRATION_JENKINS_URL}/job/public/job/launcher"
name: "launcher"

**Comment by vdelendik** [comment]
after providing valid jenkins url we still have invalid job url for default launcher
id: 1
jenkinsHost: "http://hostname/jenkins"
jobURL: "http://hostname/jenkins/job/public/job/launcher"

but actual jobURL is http://52.7.165.168/jenkins/job/launcher/.
Need review these default repo registration steps

**Comment by vdelendik** [comment]
[Uploading launcher.log…]()

**Comment by vdelendik** [comment]
fixed. need to remove all reporting-* images obligatory!

**Comment by okamara** [comment]
Verified on dev. Done.
