### ISSUE TITLE
Test result report for Job started from Jenkins is not visible in Reporting

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2236]
**Steps to reproduce**
[Make sure to specify user role used to log in to Zebrunner]
Below are the steps to reproduce the behavior:
1. Go to 'Jenkins'
2. Run Web demo test
3. Verify that Test run result is present in Reporting

**Actual behavior**
Test run result is not present in Reporting

**Expected behavior (if known)**
Test run result is present in Reporting

**Environment**
[Make sure to specify Zebrunner versions you see at login page]
UI version: 1.12.0
API (back-end) version: 1.12.1

**Comment by vdelendik** [comment]
fixed.
during the testing make sure to use QPS_PIPELINE_BRANCH=develop!

steps:
1. ./zebrunner.sh setup
2. open zafira -> test launchers
3. Select existing carina-demo and click Scan
-> RegisterRepository job is launched from the root folder  on jenkins
-> reporting_service_url and reporting_service_token registered in jenkins credentials
-> carina-demo folder with jobs generated
4. Run carina-demo/Api-Demo-Test from jenkins!
-> results should be registered successfully

**Comment by okamara** [comment]
Test run with results appears in reporting. But test session is not started. Will be created a separate bug.
