### ISSUE TITLE
Test run appears with delay in Reporting

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2237]
**Steps to reproduce**
[Make sure to specify user role used to log in to Zebrunner]
Below are the steps to reproduce the behavior:
1. Go to '.Reporting'
2. Click on 'Test Launcher'
3. In carina-demo launch Web test
4. Verify that Test run started and appears in reporting test-runs
**Actual behavior**
Test run appears in 2-3 mins after start

**Expected behavior (if known)**
Test run appears after launch

**Environment**
[Make sure to specify Zebrunner versions you see at login page]
UI version:1.12.0
API (back-end) version:1.12.1

**Comment by vdelendik** [comment]
fixed
