### ISSUE TITLE
variables.env is not changed in rabbitmq after setup

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2238]
**Description**
variables.env is not changed in rabbitmq after setup

**Steps to reproduce**
[Make sure to specify user role used to log in to Zebrunner]
Below are the steps to reproduce the behavior:
1. Start zebrunner ce setup
2. Change all passwords
3. Open config files and verify that password is updated e.g.configuration/rabbitmq/variables.env

**Actual behavior**
configuration/rabbitmq/variables.env is not changed

**Expected behavior (if known)**
configuration/rabbitmq/variables.env is updated after setup

**Environment**
[Make sure to specify Zebrunner versions you see at login page]
ui: 1.13.0.68-SNAPSHOT
server: 1.12.2.72-SNAPSHOT

**Comment by vdelendik** [comment]
fixed. change is pushed into the zebrunner/zebrunner (branch: develop)

**Comment by okamara** [comment]
Fixed.
