### ISSUE TITLE
AWS S3: Providers not available in Test Launchers

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2243]
**Description**
No available providers in Test Launcher jobs  for AWS s3

**Steps to reproduce**

1. Setup zebrunner with aws 
2. Start
3. Open Reporting
4. Click Test Launchers
5. open carina-demo Web test job 
6. Verify that providers are visible in test job

**Actual behavior**
No available providers in Test Launcher jobs 

**Expected behavior (if known)**
providers are available in Test Launcher jobs

**Environment**
UI version:1.12.0
API (back-end) version:1.12.1

**Attachments**
<img width="982" alt="Screen Shot 2020-10-07 at 6 12 54 PM" src="https://user-images.githubusercontent.com/32964663/95350646-10e7af80-08c9-11eb-8f19-3d1fce60bb1d.png">

**Comment by vdelendik** [comment]
Workaround:
Manually copy static templates from minio s3 storage to your AWS S3 bucket

cp reporting/minio-storage/configuration/minio
aws s3 cp ./data s3://MYBUCKET/ --recursive

**Comment by vdelendik** [comment]
s3-migration-tool needed which can copy above templates automaticaly

**Comment by vdelendik** [comment]
closing as won't fix a in CE this feature should be removed completely in upcoming 1.24
