### ISSUE TITLE
RabbitMQ container incorrect startup [MAC]

### ISSUE THREAD

**Issue by tsvrko** [zebrunner/reporting#2245]
After app startup via ./zebrunner.sh start logs of rabbitmq the following error appears in rabbitmq logs:

```
{"init terminating in do_boot",{error,{error,{failed_to_import_definitions,"/rabbit-definitions/001-general-definition.json.original",{could_not_read_defs,{"/rabbit-definitions/001-general-definition.json.original",eacces}}}}}}
init terminating in do_boot ({error,{error,{failed_to_import_definitions,/rabbit-definitions/001-general-definition.json.original,{could_not_read_defs,{_}}}}})

```
As soon as 001-general-definition.json.original is deleted from definitions directory and connected with it line removed from docker-compose.yml, rabbitmq container and depending on it apps are up and running.

Reprodused in master branch and never went away during past week

**Comment by vdelendik** [comment]
fixed and merged to master: https://github.com/zebrunner/reporting/pull/2246

**Comment by okamara** [comment]
Tested. Fixed.
