### ISSUE TITLE
Add Prerequisites to reporting read.me

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2248]
**Description**
Add System requirements for Reporting

**Comment by okamara** [comment]
https://github.com/zebrunner/reporting/blob/okamara-patch-1/README.md

**Comment by vdelendik** [comment]
merged into the develop branch: https://github.com/zebrunner/reporting/tree/develop
during a testing make sure default README in develop branch has such data
![image](https://user-images.githubusercontent.com/4551455/96934421-d6863100-14ca-11eb-8fa2-7cb274da84c3.png)

**Comment by dhreben** [comment]
Verified.

<img width="730" alt="Screen Shot 2020-10-23 at 13 22 14" src="https://user-images.githubusercontent.com/50950954/96992583-c609a100-1532-11eb-94b6-8d2132c7e332.png">
