### ISSUE TITLE
bash syntax error for iam-db

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2255]
```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/iam-db-init.sh
/docker-entrypoint-initdb.d/iam-db-init.sh: line 2: [: ==: unary operator expected
CREATE SCHEMA

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/sql

```

**Comment by vdelendik** [comment]
fixed. to verify just setup and start zebrunner and analyze
`docker logs -f iam-db`
-> above error shouldn't be displayed!
restart everything
again analyze iam-db logs

**Comment by okamara** [comment]
Steps:
setup and start zebrunner and analyze
docker logs -f iam-db 
Actual result: I see errors in log
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/iam-db-init.sh
/docker-entrypoint-initdb.d/iam-db-init.sh: line 2: [: ==: unary operator expected
CREATE SCHEMA

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/sql

LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  pg_cron scheduler shutting down
waiting for server to shut down....LOG:  shutting down
LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2020-10-29 12:35:21 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  pg_cron scheduler started
ERROR:  relation "zafira.databasechangeloglock" does not exist at character 22
STATEMENT:  SELECT COUNT(*) FROM zafira.databasechangeloglock

**Comment by okamara** [comment]
Can't repro after git pull last changes.
