### ISSUE TITLE
Widgets: Issue statuses and bottom text is not visible during create new widgets

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2258]
Tested via qps-infra:develop; jenkins-master:5.1-beta3;pipeline-develop
Case1:
Steps:
1.Click Add a new widget 
2.Click  PASS RATE (BAR)
3.Verify Preloading image for this widget
Actual result: Bottom text is not fully visible

Case2:
1.Click Add a new widget 
2.Click  PASS RATE (BAR)
3.Click Next
4.Select value for  "PERIOD" - Monthly
5.Verify that Top issue statuses are present 
Actual result: Top issue statuses are not present 

Case3:
Steps:
1.Click Add a new widget 
2.Click  PASS RATE (LINE), PASS RATE (PIE + LINE), TESTS IMPLEMENTATION PROGRESS
3.Verify Preloading image for this widget
Actual result: Bottom text is not fully visible
4. Click Next and verify the image for this widget
Actual result: Bottom text is not fully visible

<img width="608" alt="Screen Shot 2020-06-16 at 6 39 54 PM" src="https://user-images.githubusercontent.com/32964663/84807986-b3291200-b010-11ea-969a-d724822c6cd2.png">
<img width="875" alt="Screen Shot 2020-06-16 at 6 42 27 PM" src="https://user-images.githubusercontent.com/32964663/84808003-b91ef300-b010-11ea-8112-fceec4b7bdd7.png">
<img width="872" alt="Screen Shot 2020-06-16 at 6 43 04 PM" src="https://user-images.githubusercontent.com/32964663/84808015-bf14d400-b010-11ea-9ae0-86e2811fd614.png">

<img width="299" alt="Screen Shot 2020-06-16 at 9 09 52 PM" src="https://user-images.githubusercontent.com/32964663/84811880-313be780-b016-11ea-9d36-4f5f3bc66448.png">

**Comment by vdelendik** [comment]
closing as won't fix. it depends on device resolution
