### ISSUE TITLE
Launcher: default repo is not present in reporting

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2262]
**Steps to reproduce**
1. Install zebrunner ce or update v.1.2
2. Register organization, repo
3. Open Reporting service
4. Open Launchers
5. Verify that default repo is present in the left menu

**Actual behavior**
default repo is not present in Launchers

**Expected behavior (if known)**
default repo is present in Launchers

**Environment**
[Make sure to specify Zebrunner versions you see at login page]
UI version:1.14.0
API (back-end) version:1.14.0

**Comment by vdelendik** [comment]
closing as can't repro
