### ISSUE TITLE
Integration: Zafira report is empty after running Web or Api-Demo-Tests

### ISSUE THREAD

**Issue by dhreben** [zebrunner/reporting#2267]
**Tested on: develop branch RC build**

ui: 1.16.0.RC1
server: 1.16.0.RC2

**Test scenario:**

1.Install or update zebrunner ce
2.Set up integration with Reporting
3. Run RegisterOrganization
4.Run  RegisterRepository
4.Run Web-demo-test or Api-demo-Tests

**Actual result**: Zafira report is empty after running Web-Demo-Test

Please see screenshot:

<img width="734" alt="Screenshot 2020-11-30 at 16 30 20" src="https://user-images.githubusercontent.com/50950954/100617709-f14e8f80-332b-11eb-9673-673c93efb54f.png">

**Comment by vdelendik** [comment]
```
URL: http://3.210.50.48/api/reporting/api/tests/runs/c2508928-1a53-46f7-a2a7-cd419ecbbf57/export
Content-Type: application/json
Authorization: *****
Sending request to url: http://3.210.50.48/api/reporting/api/tests/runs/c2508928-1a53-46f7-a2a7-cd419ecbbf57/export
Response Code: HTTP/1.1 500 
Success code from [200‥500]
```

**Comment by vdelendik** [comment]
2 issues detected:
1. new variable name should be provided for s3.env
S3_ENDPOINT=http://minio:9000
->
ZEBRUNNER_AWSS3_ENDPOINT=http://minio:9000

2. htmlpublisher plugin should be upgraded till 1.25 version

**Comment by vdelendik** [comment]
1st part fixed.
2nd fix is dscribed here: https://github.com/zebrunner/jenkins-master/issues/321

**Comment by dhreben** [comment]
Fixed.

<img width="523" alt="Screenshot 2020-12-01 at 22 11 05" src="https://user-images.githubusercontent.com/50950954/100785724-1de4d300-3422-11eb-9500-305a7b1dc389.png">
