### ISSUE TITLE
3 new vars added but not used

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2269]
according to my findings iam-service works fine without recently added variables:
https://github.com/zebrunner/reporting/pull/2265/commits/6bbf9945e02ce4ee6fc4237881b2bb6ff4d527ca

we should re move it and only in case of the problem return back otherwise configuration and upgrade steps should be adjusted

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/reporting/commit/800c6869a8fffa22e7adeabaecdd14b950928932

during the test jus make sure iam-service is started and you could login to reporting, register tests and register new users inside

**Comment by okamara** [comment]
Verified. Fixed.
