### ISSUE TITLE
Add the possibility to recognize when the test was marked as passed manually.

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/reporting#2270]
**Description**
Add the possibility to recognize when the test was marked as passed manually. With the possibility to sort.

**Value**
For now, we have conflicts with the manual team. When they review failures and found that they are not reproduced manually - they marked the test as Passed. But from the Automation team perspective - we recognize that this test should be fixed. And it is almost impossible to find all such 'Marked as Passed' tests to provide fixes.
It can be a little bit different green color and with the possibility to filter by 'Passed manually'.
It is not needed to separate them somehow in reports and dashboards. 

**Additional context**
Also adding comments for each test (not the whole suite) will be very useful.

**Comment by vdelendik** [comment]
closing as moved to jira: ZEB-6126
