### ISSUE TITLE
Zebrunner test run filters should apply 'AND' when using the same column twice

### ISSUE THREAD

**Issue by FredVaugeois** [zebrunner/reporting#2271]
Here, I want to create a filter that shows every test run that was either a fail, aborted or ignored to quickly see all the problematic test runs. The problem is that the only way I found to do that is by setting "Status != 'PASSED'".

![image](https://user-images.githubusercontent.com/26579806/102621228-47357c80-410d-11eb-8bc6-79cda3df93bd.png)

 When I also add, for example, "Status != 'IN PROGRESS'", instead of making it an 'AND' and removing all the test runs that also are in progress, it simply makes the status filter useless and shows everything (maybe it takes the last filter or something), when it should instead combine the filters.
 
![image](https://user-images.githubusercontent.com/26579806/102621411-7fd55600-410d-11eb-8727-ec64160da624.png)

Two solutions are possible: either make it so that for each filter, we can add a list of values instead of a single one or simply make a rule that combines filters when they are applied on a common column.

**Comment by vdelendik** [comment]
filter were redesigned a lot in 1.20. @FredVaugeois, please test and provide your feedback
