### ISSUE TITLE
The 'Test Summary' widget does not work as intended when grouping by TEST_SUITE_NAME

### ISSUE THREAD

**Issue by FredVaugeois** [zebrunner/reporting#2273]
Basically, I want to have a report that shows me, in the last month, the number of fails/passes (and their %) in a single view for each of my projects and/or test suites.

The problem is that when I set the information like this in the 'Test Summary' widget, it does not work at all:

![image](https://user-images.githubusercontent.com/26579806/102622676-5d443c80-410f-11eb-89e9-2237875b630d.png)

![image](https://user-images.githubusercontent.com/26579806/102622686-5fa69680-410f-11eb-9320-0aaa6a502ec0.png)

It basically does not group the results by test suite, it looks like it just shows every single test run: 

![image](https://user-images.githubusercontent.com/26579806/102623181-1b67c600-4110-11eb-8f1c-860947a890f2.png)

Also, this is extremely laggy when I try to create this widget, probably because it does, actually, generate each single test run for the last month and puts it in a single table.

![image](https://user-images.githubusercontent.com/26579806/102623190-1e62b680-4110-11eb-905d-31943bb3ca3c.png)

**Comment by vdelendik** [comment]
@FredVaugeois, good point - fix will be delivered with 1.24 reporting.
btw, test suites is deprecated as it is TestNG specific data so grouping will be possible by test run name

**Comment by dhreben** [comment]
Fixed.

ui: 1.23.0.326-SNAPSHOT
server: 1.23.0.669-SNAPSHOT
