### ISSUE TITLE
Add the ability to use the interactive filter when locked on a filter preset

### ISSUE THREAD

**Issue by FredVaugeois** [zebrunner/reporting#2277]
Right now, it's impossible to dynamically filter test runs if you are filtering with a preset filter. That would be nice to add the ability to still filter some fields even when locked on a preset filter.

**Comment by vdelendik** [comment]
filtering reorganized a lot in 1.20 reporting which is part of 1.5 zebrunner-ce.
new functionality has some unfriendly use-cases but allow to apply filter and continue modification/sharing filter via urs etc
