### ISSUE TITLE
Add possibility to send reviewed result to the TestRail

### ISSUE THREAD

**Issue by imikulich** [zebrunner/reporting#2279]
**Description**
Add possibility to send reviewed and updated results of automation runs from Zebrunner to the TestRail.
**Value**
The results are marked automatically in TestRail (if configured) after execution. Then we review and update results. And we have to show these updated results in the same TestRail run.
**Additional context**
I propose adding the button to the context menu under "Mark as review". This button has to be available if TestRail integration is turned on.

**Comment by maksimsarychau** [comment]
Is it possible to increase priority for this feature to 'Critical'?

**Comment by vdelendik** [comment]
export to TestRail should be implemented soon. back-end is ready, front-end hopefully should appear in 1.21 or 1.22

**Comment by vdelendik** [comment]
in v. 1.22 back-end is finished for this operation. UI should appear in 1.24 so we can remove pipeline steps from pipeline-ce

**Comment by vdelendik** [comment]
closing as won't fix in CE version. PRO part already implemented enhanced testrail integration
