### ISSUE TITLE
Zebrunner : In case test run got deleted from zafira test run UI, it should delete the relevant screenshot/artifacts from S3 bucket and relevant places.

### ISSUE THREAD

**Issue by prasadjshimpi** [zebrunner/reporting#2280]
Zebrunner : In case test run got deleted from zafira test run UI, it should delete the relevant screenshot/artifacts from S3 bucket and relevant places.

**Comment by vdelendik** [comment]
closing as won't fix. cleanup should be done on users level if necessary
