### ISSUE TITLE
Add possibility to select should we do Re-run on the actual build or on the latest available.

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/reporting#2281]
**Description**
Add possibility to select should we do Rerun on the actual build or on the latest available.

**Value**
Currently, it is impossible to rerun failures on the required build. Zebrunner trigger rerun on the latest available build. 
But on Mobile automation often have to check some Release build with a specific build number. And we should be sure that rerun will be provided on the expected build. For now, there is only one workaround - be really careful and make rerun through Jenkins. 

**Additional context**
**It is a critical and annoying problem during all releases. And we are having a release every week.**

**Comment by vdelendik** [comment]
ticket already exists in provate repo
