### ISSUE TITLE
Add the ability to filter by project for test runs

### ISSUE THREAD

**Issue by FredVaugeois** [zebrunner/reporting#2286]
**Description**
This feature was available before the last two updates but has now been removed for some reason. There is currently no way to easily filter test runs by project (either in the normal filters and the saved filters). I know that it's possible using this screen, but it would be nice to be able to filter it directly in the filter control, like we were able to in earlier versions.

![image](https://user-images.githubusercontent.com/26579806/110126470-75346f80-7d92-11eb-834d-b279ef32ef1b.png)

**Steps to reproduce**
N/A

**Actual behavior**
No way to easily filter by project.

**Expected behavior (if known)**
Have to ability to filter by project in the filter control.

**Environment**
Reporting 1.20

**Comment by vdelendik** [comment]
project-service scope if feature of the PRO version of the reporting. in CE projects will be decommissioned at all as they are mostly labels. We consider an option to register valid "project" label but overall in CE version only single default project will be available. As about filtering we are going to provide filters by system labels like project, priority and feature soon
closing as won't win.
