### ISSUE TITLE
remove launchers support including setup procedure

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2290]
Launchers in CE version is too hard to support and maintain. Also it has too many known issues which can't be fixed so quickly. Moreover, it influence negatively onto the widgets performance.
As result we decided to remove projects supports in CE version as all.

**Comment by vdelendik** [comment]
done, changes are already pushed to repo: zebrunner; branch: develop

**Comment by okamara** [comment]
Verified, Launcher is removed.
