### ISSUE TITLE
register new cron expression to update materialized views

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2295]
LAST_365_DAYS_MATERIALIZED and TOTAL_MATERIALIZED views should be refresh once per month starting from 1.24
old cron expressions should be removed during upgrade

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/reporting/commit/5bed7beeb955817bb20a71fd32cef678622ce16d
during the testing setup zebrunner from develop, connect to the postgres and do
```
psql -U postgres postgres
set schema 'cron';
select * from job;
```
Note: actual schema and table name might differ from above steps:)
-> such 2 cron expressions should exist in db only:
`0 0 1 * *` for LAST_365_DAYS_MATERIALIZED
`15 0 1 * *` for TOTAL_MATERIALIZED

**Comment by okamara** [comment]
verified on zebrunner from dev. branch:
<img width="609" alt="Снимок экрана 2021-06-15 в 13 28 14" src="https://user-images.githubusercontent.com/32964663/122037797-9cf99180-cddd-11eb-823e-54ab3239f832.png">
