### ISSUE TITLE
replace "30 DAYS PASS RATE BY PROJECT (%)" by OWNER

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2297]
no more projects in CE so let's replace this widget on general board by grouping by OWNER(s)

**Comment by vdelendik** [comment]
done. changes can be tested using zebrunner setup from branch: develop.
reporting-service version: 1.24.0.181-SNAPSHOT+

**Comment by okamara** [comment]
Verified on zebrunner ce from dev. branch on 
ui: 1.23.0.140-SNAPSHOT
server: 1.24.0.184-SNAPSHOT
Fixed.
