### ISSUE TITLE
adjust "30 DAYS TEST DETAILS" to apply new widget templates

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2298]
1. group by OWNER is lost and should be returned
2. RUN_NAME should be unchecked in legend by default

**Comment by vdelendik** [comment]
changes applied:
![image](https://user-images.githubusercontent.com/4551455/122299387-99155e80-cf06-11eb-8043-bba72625452f.png)

it can be tested on General board after setup zebrunner using branch develop

**Comment by okamara** [comment]
Verified on develop branch.

ui: 1.23.0.140-SNAPSHOT
server: 1.24.0.184-SNAPSHOT
Fixed.
