### ISSUE TITLE
refactor "Personal" board

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2299]
1.  remove "LAST 7 DAYS PERSONAL" and "LAST 30 DAYS PERSONAL" widgets
2. move "30 DAYS TESTS PERSONAL TREND" into the top right
3. rename "LAST 24 HOURS PERSONAL" to "LAST 24 HOURS"
3. replace "LAST 24 HOURS PERSONAL FAILURES" by modern widget template and rename to "LAST 24 HOURS FAILURES"

**Comment by vdelendik** [comment]
done:
![image](https://user-images.githubusercontent.com/4551455/122299734-0b863e80-cf07-11eb-982c-d78c438a2af3.png)

changes might be tested using latest zebrunner from branch: develop

**Comment by okamara** [comment]
remove "LAST 7 DAYS PERSONAL" and "LAST 30 DAYS PERSONAL" widgets - Fixed
move "30 DAYS TESTS PERSONAL TREND" into the top right - 2nd position Fixed
rename "LAST 24 HOURS PERSONAL" to "LAST 24 HOURS" - 1st position Fixed
replace "LAST 24 HOURS PERSONAL FAILURES" by modern widget template and rename to "LAST 24 HOURS FAILURES" - Fixed.
<img width="1228" alt="Снимок экрана 2021-06-17 в 14 08 08" src="https://user-images.githubusercontent.com/32964663/122385827-e977d500-cf75-11eb-87b1-289eb5706679.png">
