### ISSUE TITLE
Restore hidden flag for system boards

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2300]
below 3 dashboards should become hidden again in CE:
Failures analysis
Stability
User Performance

based on latest change they became visible again

**Comment by vdelendik** [comment]
done. adjusted back-end to register in DB valid HIDDEN=TRUE attribute.
But going to submit a ticket to front-end as boards still are displayed on UI.

to test fix for this particular case we have to setup zebrunner using develop branch from scratch and review `dashboards` table in DB:
```
docker exec -ti postgres bash;
psql -U postgres postgres
set schema 'zafira';
select * from dashboards;
```

-> for Failures analysis, Stability and User Performance dashboards `hidden=t`, i.e. true
![image](https://user-images.githubusercontent.com/4551455/122302356-a92f3d00-cf0a-11eb-8364-3bec5a514a14.png)

**Comment by okamara** [comment]
Verified on dev. branch. Fixed.
<img width="850" alt="Снимок экрана 2021-06-18 в 13 46 55" src="https://user-images.githubusercontent.com/32964663/122549914-b13aca00-d03b-11eb-9cff-e1982632e7a4.png">
