### ISSUE TITLE
Add column Username to FAILURE DETAILS table

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2301]
**Description**
Add column Username to FAILURE DETAILS table

**Steps to reproduce**

1. Go to 'Failures analysis' widget from Personal ->LAST 24 HOURS FAILURES-> View

**Actual behavior**
FAILURE DETAILS table contains failures for all users, but no Users column and details

**Expected behavior (if known)**
FAILURE DETAILS table contains failures for all users, need to add users column for more clarity before RUN column

**Environment**
zebrunner ce from dev branch
ui: 1.23.0.140-SNAPSHOT
server: 1.24.0.184-SNAPSHOT

**Attachments**
<img width="1278" alt="Снимок экрана 2021-06-17 в 13 47 58" src="https://user-images.githubusercontent.com/32964663/122383197-48881a80-cf73-11eb-9f0c-8bd94dff10e8.png">

**Comment by vdelendik** [comment]
let's review and import latest free widget templates from PRO version

**Comment by vdelendik** [comment]
closing as won't fix in CE version.
