### ISSUE TITLE
Default dashboards are not editable

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2303]
**Steps to reproduce**

1. Go to Dashboards page as admin, superadmin user
2. Click on default dashboard e.g 'General'
3. Verify that it is possible to Edit, Delete dashboard and widgets are editable too

**Actual behavior**
Default dashboards are not editable

**Expected behavior (if known)**
it is possible to Edit, Delete dashboard and widgets are editable too
<img width="1130" alt="Снимок экрана 2021-06-24 в 13 00 29" src="https://user-images.githubusercontent.com/32964663/123244004-30bd1300-d4ec-11eb-95eb-a11a41e395c6.png">

**Environment**
zebrunner ce from develop branch

ui: 1.24.0.148-SNAPSHOT
server: 1.24.0.186-SNAPSHOT

**Comment by vdelendik** [comment]
it should be fixed now
