### ISSUE TITLE
Re-add the ability to filter by TestSuite and Project in the test viewer 

### ISSUE THREAD

**Issue by FredVaugeois** [zebrunner/reporting#2305]
Previously, we were able to filter by test suite and Project in the test viewer, but this has been removed in version 1.4. I would like to get this feature back to be able to create custom filters with these attributes.

![image](https://user-images.githubusercontent.com/26579806/123662854-d67dc400-d803-11eb-9fab-15074514f80b.png)

**Comment by vdelendik** [comment]
latest filters might save any text to look for suite/job name
