### ISSUE TITLE
Add possibility to execute or re-run job in the specific time or with some delay up to 12 hours. 

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/reporting#2308]
**Description**
Add possibility to execute or re-run job in the specific time or with some delay up to 12 hours. 

**Value**
In Launcher functionality it will be really useful to have the possibility to set the exact time of execution or re-running some jobs without updating the schedule. Or have a delay if we know that currently there will be a queue of runs. Really useful for mobile testing.

**Comment by vdelendik** [comment]
closing as won't fix. it might be organized in PRO only
