### ISSUE TITLE
502 error Unable to start Reporting

### ISSUE THREAD

**Issue by dhreben** [zebrunner/reporting#2310]
**Test scenario:**

1.Git clone from develop
2.nano .env and change to
TAG_REPORTING_UI=1.25.0.157-SNAPSHOT
TAG_REPORTING_SERVICE=1.24.0.203-SNAPSHOT
3../zebrunner.sh setup

**Actual result :**  Unable to start Reporting.
ERROR: Couldn't find env file: /home/ec2-user/tools/zebrunner/reporting/configuration/postgres/variables.env

**Comment by vdelendik** [comment]
@dhreben, issue should be fixed by registering in reporting/.env concrete `3.8-management` rabbitmq version.
please, redeploy from scratch using zebrunner branch: develop.
Also, test carefully new integrations, they seems to be broken as minimal for Jenkins

**Comment by dhreben** [comment]
Fixed.
