### ISSUE TITLE
Add possibility for creating a dashboard in Zebrunner that reflects the dynamics of the TestRail suites implementation progress for one month, quarter, year based on Testrail details

### ISSUE THREAD

**Issue by maksimsarychau** [zebrunner/reporting#2311]
**Description**
Add possibility for creating a dashboard in Zebrunner that reflects the dynamics of the TestRail suites implementation progress for one month, quarter, year based on Testrail and unique tests cases details. With the possibility of filtering by platform. 

**Value**
It will show team progress for the management and customers for the month, quarter, etc.

**Comment by vdelendik** [comment]
closing as won't fix. enhancements registered in PRO
