### ISSUE TITLE
made FAILURES BY RUN widget hidden by default

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2318]
During set of discussions we decided to make `FAILURES BY RUN` widget template as hidden by default.

**Comment by vdelendik** [comment]
done. make sure to setup CE from develop branch and verify that template is not available.
1. try to generate mew widget in dashboards
-> there is no `FAILURES BY RUN` widget template among the available list

**Comment by okamara** [comment]
Verified on dev. ,fixed.
