### ISSUE TITLE
unable to setup independent setup via SSL

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2328]
**Description**
In read.me described that user can independent setup and start reporting with https
https://github.com/zebrunner/reporting/blob/master/README.md

**Steps to reproduce**
1.  git clone --recurse-submodule https://github.com/zebrunner/reporting.git && cd reporting && ./zebrunner.sh setup
Provide required details for https protocol
2. Start services ./zebrunner.sh start
3. https://hostname:port for secured protocol
**Actual behavior** reporting page is opened in browser  with https

**Expected behavior ** reporting page is not opened properly in browser  with https
[A clear and concise description of what you expected to happen.]

<img width="1153" alt="Снимок экрана 2021-10-28 в 11 22 18" src="https://user-images.githubusercontent.com/32964663/139216628-44c1221c-2da7-43ab-a826-4a15ea1234ef.png">

**Comment by vdelendik** [comment]
done. to test such scenarios should be tested:
1. http setup using CE
2. http setup of reporting independent
3. https setup using CE (only global nginx under ssl).
-> inside `./reporting/configuration/zebrunner-proxy/nginx.conf` ssl related lines still commented!
4. https setup of reporting independent
-> inside `./configuration/zebrunner-proxy/nginx.conf` ssl related lines uncommented! Also `listen 80 ssl;` declared

**Comment by okamara** [comment]
verified, fixed
