### ISSUE TITLE
track elasticsearch-oss and logstash-oss repo to upgrade asap onto the latest verions

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2335]
https://www.docker.elastic.co/r/elasticsearch/elasticsearch-oss
https://www.docker.elastic.co/r/logstash/logstash-oss

**Comment by vdelendik** [comment]
based on our investigation we plan to provide patched elasticsearch and logstash images under zebrunner organization with patched log4j2x inside. ETA - end of Jan

**Comment by vdelendik** [comment]
done, we switched to the 7.16.3 [elasticsearch](https://hub.docker.com/layers/elasticsearch/library/elasticsearch/7.16.3/images/sha256-bc693247a6b0eb903238e3c06671db10b37f0fcb32a76b6cc9ae8a6b1755df64?context=explore)
and [logstash](https://hub.docker.com/layers/logstash/library/logstash/7.16.3/images/sha256-fd6c62d6a514d0e647918462ec367884589a0a57985388f31c6e71a01a1b43e3?context=explore)

**Comment by okamara** [comment]
Verified, fixed.
