### ISSUE TITLE
Video is not present in web jobs

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2336]
**Description**
Video is not present in web jobs

**Steps to reproduce**
Setup zebrunner ce from develop branch
1. Create Organization
2. Register repo
3. Run Web demo test
4. Verify that video is available and visible 

**Actual behavior**
Video is not present

**Expected behavior (if known)**
Video is present and available

**Comment by vdelendik** [comment]
fixes delivered in scope of https://github.com/zebrunner/pipeline-ce/issues/219. closing completely as testing will be done as part of pipeline project too.
