### ISSUE TITLE
VNC is not working on 2.0 master and 2.1 develop branches of CE

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2339]
**Example of steps:**
setup CE using master branch (2.0 release in master branch)
do basic acceptance
run Web demo test 
**-> Verify that VNC video is working 
-> VNC video is not working** 
switch to the develop branch and pull sub-modules recursively
git checkout develop
git pull --recurse-submodules
run ./zebrunner.sh upgrade, confirm action and services restart
run Web demo test 
**-> Verify that VNC video is working 
-> VNC video is not working** 
<img width="1375" alt="Снимок экрана 2022-07-28 в 15 08 52" src="https://user-images.githubusercontent.com/32964663/181530116-b2a73035-f341-4d29-aa5c-c3ff96243cfb.png">

**Comment by vdelendik** [comment]
closing as won't fix. it will be known limitation for CE version.
in PRO version we provide full support of VNC for web and mobile tests...
