### ISSUE TITLE
Agent: rerun failures with dependent methods is broken in TestNG

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2342]
TestNG agent seems just use method state to find out which one to re-execute. As result we don’t include to re-run base methods on which failed ones depends. It blocks completely rerun and corrupt TestNG JVM:

org.testng.TestNGException: 
Method "PremiumMealGoalsTest.testEnableMealGoalsDefault()[pri:0, instance:com.myfitnesspal.qa.test.premium.PremiumMealGoalsTest@3e60be48]" depends on nonexistent method "com.myfitnesspal.qa.test.premium.PremiumMealGoalsTest.testDisabledMealGoals"
 

Previously on the finish we recalculate all failed methods and for each of them all based methods as well to rerun everything correctly. 

In scope of the ticket we have to find the root cause of this problem and fix if possible. Workaround steps were provided to UA team

**Comment by vdelendik** [comment]
fixed in 1.28 image.
during the testing let's execute set of api jobs and do rerun failures for those where failures were detected.
-> @okamara new reruns should execute only previously failed tests

**Comment by okamara** [comment]
verified, fixed. Need run again after fix cron jobs.
