### ISSUE TITLE
warn about shutdown and confirm this action

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2343]
in scope of independent setup we have to warn about shutdown operation and proceed only if confirmed by user.
Make sure do not ask twice if reporting is configured as part of CE

**Comment by vdelendik** [comment]
fixed one more time. to cover all scenarios I can recommend independent setup and such steps:
1. no SHUTDOWN_CONFIRMED env var
-> confirmation should be displayed

2. register in advance in current shell `export SHUTDOWN_CONFIRMED=0`
-> confirmation should be displayed

3. register in advance in current shell `export SHUTDOWN_CONFIRMED=1`
-> shutdown should happen without confirmation

**Comment by okamara** [comment]
verified, fixed.
