### ISSUE TITLE
unable to request PRO demo from banner

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#2346]
using 1.28.0 reporting we can't request demo for PRO:
![image](https://user-images.githubusercontent.com/4551455/235155309-4083f7d2-799d-4106-b1f1-0c640b406889.png)

![image](https://user-images.githubusercontent.com/4551455/235155529-60a17670-cd0a-4b7d-b8b9-547e5eeb00fb.png)

![image](https://user-images.githubusercontent.com/4551455/235155616-470a0566-a022-43b2-9d01-75966c9075a0.png)

let's remove banner at all.

**Comment by danymill** [comment]
https://gitlab.com/zebrunner/ce/reporting-ui/-/merge_requests/739

**Comment by vdelendik** [comment]
merged. we have to build new version of reporting-ui and integrate into https://github.com/zebrunner/reporting/blob/49731105c50e76b2227b582d300fe0b036aa40b4/.env.original#L1

**Comment by vdelendik** [comment]
done: zebrunner/reporting-service:1.29.0.329-SNAPSHOT
testing should happen using CE, branch develop

**Comment by vdelendik** [comment]
tested successfully. also submitted ticket to bump up onto the released version
