### ISSUE TITLE
Create the ability to add results to several tests at once

### ISSUE THREAD

**Issue by kdaroshka** [zebrunner/reporting#721]
Description: it would be much easiar to review and add results to several tests at once. In my opinion tests in test run could have checkboxes, so user can select several tests and add same result to all of them at once (attach link to the same JIRA ticket, or add same comment to all selected tests)

**Comment by nsidorevich** [comment]
Let's narrow down set of features we'd like to provide to be applied in batch mode and get back to this one.

**Comment by vdelendik** [comment]
already delivered
