### ISSUE TITLE
introduce dedicated icon for player when video is not available

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#897]
something like this:
![image](https://user-images.githubusercontent.com/4551455/42631875-2106b498-85e4-11e8-8c74-e0eb751d2506.png)

**Comment by nsidorevich** [comment]
Assigned to @danymill , however we need such icon first @hursevich , once we'll get it - should not be a big deal to implement

**Comment by vdelendik** [comment]
already fixed
