### ISSUE TITLE
Investigate if we can benefit from ElasticSearch features in terms of analyzing test log data

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#962]
please review if we can use indexed zafira logs better. I'd like to have a search by text like an error or stacktrace or similar based on test context only

**Comment by nsidorevich** [comment]
Let's talk over this one and see if this one is still relevant and how.

**Comment by nsidorevich** [comment]
We need to additionally discuss this one to better understand what exactly we expect from this one.

**Comment by vdelendik** [comment]
moved into another repo
