### ISSUE TITLE
Distinct functionality allowing to start comments threads for test run (not via review functionality as it is now)

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/reporting#965]
**Description (original):**
For now we have just a regular text message as result when we received "undefined failure" or "compilation failure" this message will be displayed even after successful rerun.

Globally we want to keep all these messages but looks like we have to define better UI strategy to provide for end user info that this comment was generated for previous run.
Maybe add date for message or disable test  which related to previous runs

**Attachments:**
![image](https://user-images.githubusercontent.com/8956214/68955493-38c4b500-07d7-11ea-9b77-75f16f403b4d.png)

**UPD 10-15-2019:** We'll need to additionally discuss this one.

**Comment by hursevich** [comment]
Let's discuss that in details.

**Comment by vdelendik** [comment]
closing as won't fix
