### ISSUE TITLE
Test artifacts comparison view (image, video etc)

### ISSUE THREAD

**Issue by nazarenkAV** [zebrunner/reporting#974]
As a user on compare testruns view I want to have a possibility to compare video for each test. If there are difference in test results then button with video comparison should be presented. When user clicks on this button he should be redirected to the page with 2 videos blocks and one block with logs. After clicking on log item both video should be scrolled and show picture according log action.

**Comment by vdelendik** [comment]
Let's prioritize it to be able to compare our tests artifacts easily: status, logs, screenshots, video etc

**Comment by nsidorevich** [comment]
UI needed here.

**Comment by vdelendik** [comment]
closing as won't fix in CE. Appropriate feature should be available in PRO version only
